version: '3'

services:
  db:
    container_name: sveltekit_db
    image: postgres:15.1
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lordran_dev
      - POSTGRES_PASSWORD=lordran_dev
      - POSTGRES_DB=sveltekit_db
    ports:
      - "5432:5432"

  pgadmin:
    depends_on:
      - db
    container_name: pgadmin
    image: dpage/pgadmin4:8
    environment:
      - PGADMIN_DEFAULT_EMAIL=lordran@lordran.dev
      - PGADMIN_DEFAULT_PASSWORD=lordran_dev
    ports:
      - "80:80"

volumes:
  pgdata: